# Generated by Django 4.1.7 on 2026-05-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_role_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
