# Generated by Django 4.1.7 on 2026-05-27 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_role_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('transaction', '거래내역'), ('secretary', '서기파일'), ('other', '기타')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '업로드 파일',
                'verbose_name_plural': '업로드 파일 목록',
            },
        ),
        migrations.CreateModel(
            name='TransactionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('bank_name', models.CharField(max_length=50)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_file', to='app.uploadedfile')),
            ],
            options={
                'verbose_name': '거래내역 파일',
                'verbose_name_plural': '거래내역 파일 목록',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('deposit', '입금'), ('withdrawal', '출금')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.transactionfile')),
            ],
            options={
                'verbose_name': '거래내역',
                'verbose_name_plural': '거래내역 목록',
                'ordering': ['-transaction_at'],
            },
        ),
    ]
