# Generated by Django 4.1.7 on 2026-06-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_uploadedfile_transactionfile_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
