# Generated by Django 4.1.7 on 2026-07-05 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_transaction_transactionfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('bank_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '거래내역 원장',
                'verbose_name_plural': '거래내역 원장 목록',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='TransactionUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='app.transactionledger')),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_upload', to='app.uploadedfile')),
            ],
            options={
                'verbose_name': '거래내역 업로드',
                'verbose_name_plural': '거래내역 업로드 목록',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('deposit', '입금'), ('withdrawal', '출금')], max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.transactionledger')),
                ('source_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app.transactionupload')),
            ],
            options={
                'verbose_name': '거래내역',
                'verbose_name_plural': '거래내역 목록',
                'ordering': ['-transaction_at'],
            },
        ),
    ]
