# Generated by Django 4.1.7 on 2026-07-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_transactionledger_transactionupload_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('transaction', '거래내역'), ('secretary', '서기파일'), ('receipt', '영수증'), ('other', '기타')], max_length=50),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transactions', models.ManyToManyField(blank=True, related_name='receipts', to='app.transaction')),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='app.uploadedfile')),
            ],
            options={
                'verbose_name': '증빙 자료',
                'verbose_name_plural': '증빙 자료 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
